{{- if and .Values.enabled .Values.clusterRole.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.clusterRole.namespace }}
  name: {{ .Values.clusterRole.name }}
rules:
  - apiGroups: [""]          # "" indicates the core API group
    resources: ["pods", "services", "ingresses", "ingressclasses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "watch", "list"]
{{- end }}