{{- if and .Values.config.enabled .Values.config .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.name" . }}-cm
data:
  {{- with .Values.config.content }}
  config.yaml: |
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
