{{- if eq (include "k8s-info-cron-service.k8sVersionCheck" .) "false" }}
  {{- fail "Unsupported kubernetes version" }}
{{- else  if .Values.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "service.name" . }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  schedule: {{ required ".cronString is required!" .Values.cronString | quote }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        metadata:
          annotations:
            {{- with .Values.annotations }}
            {{ toYaml . | nindent 12}}
            {{- end }}
          labels:
            sidecar.istio.io/inject: "false"
        spec:
          {{- if or .Values.serviceAccount.enabled .Values.serviceAccount.name }}
          serviceAccountName: {{ include "k8s-info-cron-service.serviceAccountName" . }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ include "service.name" . }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              image: "{{ required "Image repository is required!" (tpl .Values.image.repository .) }}:{{ required "Image tag is required!" .Values.image.tag }}"
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              env:
              {{- range $key, $value := $.Values.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              command:
                {{- toYaml .Values.command | nindent 16 }}
              args:
                {{- toYaml .Values.args | nindent 16 }}
              envFrom:
                - secretRef:
                    name: {{ include "k8s-info-cron-service.secretName" . }}
              volumeMounts:
              {{- if and .Values.config.enabled .Values.config }}
                - name: {{ include "service.name" . }}-config
                  mountPath: {{ required "config.mountPath required when config enabled!" .Values.config.mountPath }}
                  subPath: config.yaml
              {{- end }}
              {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
          {{- if and .Values.config.enabled .Values.config }}
            - name: {{ include "service.name" . }}-config
              configMap:
                name: {{ include "service.name" . }}-cm
                defaultMode: 0400
          {{- end }}
          {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
