{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-info-cron-service.secretName" . }}
type: Opaque
stringData:
  AAT: {{ required "Secret created without providing an application token!" .Values.secret.applicationToken | quote }}
{{- end }}
