{{- if and .Values.enabled .Values.serviceAccount .Values.serviceAccount.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "k8s-info-cron-service.serviceAccountName" . }}
{{- end }}
